.DEFAULT_GOAL := all

PREFIX ?= /usr

FC := gfortran
LDFLAGS := -B/usr/lib/x86_64-linux-gnu -L$(PREFIX)/lib -lgfortran -lnetcdff -llapack
FFLAGS  := -c -Wall -I$(PREFIX)/include -L$(PREFIX)/lib

EXECUTABLE = analogue.out
prog.f90   = analogue.f90
prog.o     = analogue.o

netcdf = netcdf.mod


.PHONY: all
all: clean build

.PHONY: build
build: $(EXECUTABLE)

config.o: config.f90
	$(FC) config.f90 $(FFLAGS)

config.mod: config.o
	@true

eofs.o: eofs.f90
	$(FC) eofs.f90 $(FFLAGS)

eofs.mod: eofs.o
	@true

read.o: read.f90
	$(FC) read.f90 $(FFLAGS)

read.mod: read.o
	@true

distance.o: distance.f90
	$(FC) distance.f90 $(FFLAGS)

distance.mod: distance.o
	@true

routines.o: routines.f90 read.mod distance.mod
	$(FC) routines.f90 $(FFLAGS)

routines.mod: routines.o
	@true

$(prog.o): config.mod routines.mod eofs.mod $(prog.f90)
	$(FC) $(prog.f90) $(FFLAGS)

$(EXECUTABLE): $(prog.o) config.o read.o distance.o routines.o eofs.o
	$(FC) $(EXECUTABLE) read.o config.o distance.o routines.o eofs.o $(prog.o) $(FFPATH) $(LDFLAGS) 


.PHONY: clean
clean:
	rm -f *.o $(EXECUTABLE)

